name: onboarding-workflow

on:
  issues:
    types:
      - closed
  
  workflow_dispatch:
    inputs:
      employee-name: 
        description: 'Name of the employee that will be onboarded'
        required: true
        default: ''

jobs:
  provision-employee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get issue creator
        id: employee-name-output
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(`Employee to onboard :tada: ${{ github.event.issue.title }}`);
            console.log(`Label ${{ github.event.issue.labels[0].name}} `);
            if ("${{ github.event_name }}" == "issues") {
              console.log(`Workflow is triggerd by an issue `);

              if (${{ github.event.issue.labels[0].name }} == 'onboard') {
                console.log(`Employee to onboard: [${{ github.event.issue.title }}]`);
                return github.event.issue.user.login;
              } 
              else {
                console.log('No onboarding issue found');
                return '';
              }
            }
            return "${{ github.event.inputs.employee-name }}";

      - name: Create repository for employee
        env:
          GITHUB_TOKEN: ${{ secrets.EXTENDED_GITHUB_TOKEN }}
        run: gh repo create renevanosnabrugge/${{ steps.employee-name-output.outputs.result }} --public 